export const FETCHING_MOVIES = "FETCHING_MOVIES";
export const FETCHING_MOVIES_SUCCESS = "FETCHING_MOVIES_SUCCESS";
export const FETCHING_MOVIES_FAILURE = "FETCHING_MOVIES_FAILURE";
export const POST_FAVORITES = "POST_FAVORITES";
export const ADD_FAVORITES = "ADD_FAVORITES";
export const CHANGE_CONNECTION_STATUS = "CHANGE_CONNECTION_STATUS";
export const REMOVE_FROM_ACTION_QUEUE = "REMOVE_FROM_ACTION_QUEUE";
